---
# tasks file for arillso.users

- name: add OS specific variables
  include_vars: '{{ loop_vars }}'
  with_first_found:
    - files:
        - '{{ distribution }}-{{ distribution_verion }}.yml'
        - '{{ distribution }}-{{ distribution_major_version }}.yml'
        - '{{ distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - '{{ ansible_system }}.yml'
        - 'defaults.yml'
      paths:
        - 'vars'
  loop_control:
    loop_var: loop_vars
  vars:
    distribution: '{{ ansible_distribution }}'
    distribution_verion: '{{ ansible_distribution_version }}'
    distribution_major_version: '{{ ansible_distribution_major_version }}'
  tags:
    - configuration
    - packages

- block:
    - name: add host users
      set_fact:
        users: '{{ users | union(users_list_host) }}'
      when: users_list_host is defined

    - name: add group users
      set_fact:
        users: '{{ users | union(users_list_group) }}'
      when: users_list_group is defined

  when: users is defined
  tags:
    - configuration

- name: include distribution tasks
  include_tasks: '{{ loop_distribution }}'
  with_first_found:
    - files:
        - '{{ distribution }}-{{ distribution_verion }}.yml'
        - '{{ distribution }}-{{ distribution_major_version }}.yml'
        - '{{ distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - '{{ ansible_system }}.yml'
        - 'defaults.yml'
      paths:
        - 'distribution'
  loop_control:
    loop_var: loop_distribution
  vars:
    distribution: '{{ ansible_distribution }}'
    distribution_verion: '{{ ansible_distribution_version }}'
    distribution_major_version: '{{ ansible_distribution_major_version }}'
  tags:
    - configuration
